name: 'madrileno_newsletter_dbt'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'madrileno_newsletter_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  madrileno_newsletter_dbt:
  
    bronze:
      +materialized: view
      +schema: bronze
      +tags: ['bronze']

    silver:
      +materialized: view
      +schema: silver
      +tags: ['silver']

    gold:
      +materialized: view
      +schema: gold
      +tags: ['gold']